// ComposerViewModel.swift
// BioNaural
//
// @Observable view model managing the 5-step sound creation flow.
// Tracks user selections across all steps, drives live audio preview
// by controlling the AudioEngine layers as the user builds their
// composition, and persists the final result to SwiftData.

import SwiftUI
import SwiftData
import BioNauralShared
import OSLog

// MARK: - ComposerViewModel

@Observable
@MainActor
final class ComposerViewModel {

    // MARK: - Step Tracking

    /// Current step index (0-4).
    var currentStep: Int = 0

    /// Total number of steps in the creation flow.
    let totalSteps: Int = 5

    // MARK: - Step 1: Brain State

    var selectedBrainState: FocusMode?

    // MARK: - Step 2: Soundscape

    var selectedAmbientBed: String?
    var selectedDetailTexture: String?

    // MARK: - Step 3: Melodic Layer

    var selectedInstruments: Set<Instrument> = []
    var brightness: Double = Theme.Compose.Defaults.brightness
    var density: Double = Theme.Compose.Defaults.density

    // MARK: - Step 4: Space & Mix

    var reverbWetDry: Float = Theme.Compose.Defaults.reverbWetDry
    var binauralVolume: Double = Theme.Compose.Defaults.binauralVolume
    var ambientVolume: Double = Theme.Compose.Defaults.ambientVolume
    var melodicVolume: Double = Theme.Compose.Defaults.melodicVolume

    // MARK: - Step 5: Save

    var compositionName: String = ""
    var durationMinutes: Int = Theme.Compose.Defaults.durationMinutes
    var isAdaptive: Bool = false

    // MARK: - Preview State

    private(set) var isPreviewPlaying: Bool = false

    // MARK: - Dependencies

    private let audioEngine: any AudioEngineProtocol

    // MARK: - Initialization

    init(audioEngine: any AudioEngineProtocol) {
        self.audioEngine = audioEngine
    }

    // MARK: - Brain State Selection (Step 1)

    func selectBrainState(_ mode: FocusMode) {
        selectedBrainState = mode

        // Set defaults from the mode
        brightness = defaultBrightness(for: mode)
        density = defaultDensity(for: mode)
        durationMinutes = defaultDuration(for: mode)

        // Set default instruments
        selectedInstruments = defaultInstruments(for: mode)

        // Auto-generate default name
        updateAutoName()

        // Start binaural preview
        do {
            try audioEngine.setup()
            try audioEngine.start(mode: mode)
            isPreviewPlaying = true
        } catch {
            Logger.audio.error("Preview start failed: \(error.localizedDescription)")
        }
    }

    // MARK: - Soundscape Selection (Step 2)

    func selectAmbientBed(_ bedName: String?) {
        selectedAmbientBed = bedName
        updateAutoName()

        guard let engine = audioEngine as? AudioEngine else { return }
        if let bedName,
           let bed = AmbientBed(rawValue: bedName) {
            // Use the mapped file name, not the raw enum value
            engine.ambienceLayer?.play(bedName: bed.fileName)
        } else if let bedName {
            // Fallback: try the raw name directly
            engine.ambienceLayer?.play(bedName: bedName)
        } else {
            engine.ambienceLayer?.stop()
        }
    }

    func selectDetailTexture(_ textureName: String?) {
        selectedDetailTexture = textureName
    }

    // MARK: - Melodic Preferences (Step 3)

    func toggleInstrument(_ instrument: Instrument) {
        if selectedInstruments.contains(instrument) {
            // Don't allow deselecting the last instrument
            if selectedInstruments.count > 1 {
                selectedInstruments.remove(instrument)
            }
        } else {
            selectedInstruments.insert(instrument)
        }
        updateAutoName()
        updateMelodicPreview()
    }

    func updateBrightness(_ value: Double) {
        brightness = value
        debouncedMelodicUpdate()
    }

    func updateDensity(_ value: Double) {
        density = value
        debouncedMelodicUpdate()
    }

    // MARK: - Space & Mix (Step 4)

    func updateReverbWetDry(_ value: Float) {
        reverbWetDry = value
        guard let engine = audioEngine as? AudioEngine else { return }
        engine.reverb?.wetDryMix = value
    }

    func updateBinauralVolume(_ value: Double) {
        binauralVolume = value
        audioEngine.parameters.binauralVolume = value
    }

    func updateAmbientVolume(_ value: Double) {
        ambientVolume = value
        audioEngine.parameters.ambientVolume = value
    }

    func updateMelodicVolume(_ value: Double) {
        melodicVolume = value
        audioEngine.parameters.melodicVolume = value
    }

    // MARK: - Save (Step 5)

    func save(in context: ModelContext) -> CustomComposition? {
        guard let mode = selectedBrainState else { return nil }

        let name = compositionName.isEmpty ? autoGeneratedName : compositionName

        let composition = CustomComposition(
            name: name,
            brainState: mode.rawValue,
            beatFrequency: mode.defaultBeatFrequency,
            carrierFrequency: mode.defaultCarrierFrequency,
            ambientBedName: selectedAmbientBed,
            detailTextureName: selectedDetailTexture,
            instruments: selectedInstruments.map(\.rawValue),
            brightness: brightness,
            density: density,
            reverbWetDry: reverbWetDry,
            binauralVolume: binauralVolume,
            ambientVolume: ambientVolume,
            melodicVolume: melodicVolume,
            durationMinutes: durationMinutes,
            isAdaptive: isAdaptive
        )

        context.insert(composition)
        stopPreview()
        return composition
    }

    // MARK: - Preview Control

    func stopPreview() {
        if isPreviewPlaying {
            audioEngine.stop()
            isPreviewPlaying = false
        }
    }

    // MARK: - Navigation

    var canAdvance: Bool {
        switch currentStep {
        case 0: return selectedBrainState != nil
        default: return true
        }
    }

    func advance() {
        guard currentStep < totalSteps - 1 else { return }
        currentStep += 1
    }

    func goBack() {
        guard currentStep > 0 else { return }
        currentStep -= 1
    }

    // MARK: - Private Helpers

    private var melodicUpdateWorkItem: DispatchWorkItem?

    private func debouncedMelodicUpdate() {
        melodicUpdateWorkItem?.cancel()
        let work = DispatchWorkItem { [weak self] in
            Task { @MainActor in
                self?.updateMelodicPreview()
            }
        }
        melodicUpdateWorkItem = work
        DispatchQueue.main.asyncAfter(
            deadline: .now() + Theme.Compose.melodicDebounceInterval,
            execute: work
        )
    }

    private func updateMelodicPreview() {
        guard let engine = audioEngine as? AudioEngine,
              let mode = selectedBrainState else { return }

        let instrumentSet = selectedInstruments
        let tolerance = Theme.Compose.Defaults.filterTolerance
        let brightnessRange = (brightness - tolerance)...(brightness + tolerance)
        let densityRange = (density - tolerance)...(density + tolerance)

        // Filter from the sound library
        let candidates = engine.soundLibrary.allSounds.filter { sound in
            guard sound.modeAffinity.contains(mode) else { return false }
            guard instrumentSet.contains(sound.instrument) else { return false }
            guard brightnessRange.contains(sound.brightness) else { return false }
            guard densityRange.contains(sound.density) else { return false }
            return true
        }

        // Fallback: widen ranges if no candidates
        let finalCandidates: [SoundMetadata]
        if candidates.isEmpty {
            finalCandidates = engine.soundLibrary.allSounds.filter { sound in
                sound.modeAffinity.contains(mode) && instrumentSet.contains(sound.instrument)
            }
        } else {
            finalCandidates = candidates
        }

        if let best = finalCandidates.first {
            engine.melodicLayer?.crossfadeTo(soundID: best.id)
        }
    }

    private var autoGeneratedName: String {
        var parts: [String] = []

        if let bed = selectedAmbientBed {
            parts.append(bed.capitalized)
        }

        if let firstInstrument = selectedInstruments.sorted(by: { $0.rawValue < $1.rawValue }).first {
            parts.append(firstInstrument.rawValue.capitalized)
        }

        if let mode = selectedBrainState {
            parts.append(mode.displayName)
        }

        return parts.isEmpty ? "New Composition" : parts.joined(separator: " + ")
    }

    private func updateAutoName() {
        if compositionName.isEmpty || compositionName == autoGeneratedName {
            compositionName = autoGeneratedName
        }
    }

    private func defaultBrightness(for mode: FocusMode) -> Double {
        Theme.Compose.ModeDefaults.brightness(for: mode)
    }

    private func defaultDensity(for mode: FocusMode) -> Double {
        Theme.Compose.ModeDefaults.density(for: mode)
    }

    private func defaultDuration(for mode: FocusMode) -> Int {
        mode.defaultDurationMinutes
    }

    private func defaultInstruments(for mode: FocusMode) -> Set<Instrument> {
        switch mode {
        case .sleep:       return [.pad, .strings]
        case .relaxation:  return [.pad, .piano]
        case .focus:       return [.piano, .pad]
        case .energize:    return [.guitar, .percussion]
        }
    }
}

// MARK: - Additional Theme.Compose Tokens

extension Theme.Compose {
    /// Debounce interval for melodic slider changes (seconds).
    static let melodicDebounceInterval: TimeInterval = 0.5
}
