// UserModelBuilder.swift
// BioNaural
//
// Background learning system that builds a full behavioral model from
// session history, HealthKit data, and check-in patterns. All on-device.
// No network dependencies. Protocol-based for testability.

import Foundation
import BioNauralShared
import SwiftData

// MARK: - Session Recommendation

/// Pre-session suggestion generated by the user model, including mode,
/// duration, and sound preference overrides based on current context.
public struct SessionRecommendation: Codable, Sendable, Equatable {

    /// Suggested session mode based on time of day, biometric context, and history.
    public let suggestedMode: FocusMode

    /// Suggested duration in seconds, based on the user's typical session length
    /// for this mode at this time of day.
    public let suggestedDuration: TimeInterval

    /// Predicted mood state (0.0 = wired, 1.0 = calm) based on patterns.
    public let moodPrediction: Double?

    /// Sound tag weight overrides derived from cross-signal correlations.
    /// These are merged with the base SoundProfile at sound selection time.
    public let soundPreferenceOverrides: [String: Double]

    /// Human-readable explanation for why this recommendation was made.
    /// Shown to the user in the pre-session flow.
    public let reasoning: String

    /// Confidence in this recommendation (0.0 - 1.0), based on data quantity.
    public let confidence: Double

    public init(
        suggestedMode: FocusMode,
        suggestedDuration: TimeInterval,
        moodPrediction: Double?,
        soundPreferenceOverrides: [String: Double],
        reasoning: String,
        confidence: Double
    ) {
        self.suggestedMode = suggestedMode
        self.suggestedDuration = suggestedDuration
        self.moodPrediction = moodPrediction
        self.soundPreferenceOverrides = soundPreferenceOverrides
        self.reasoning = reasoning
        self.confidence = confidence
    }
}

// MARK: - User Behavioral Patterns

/// Persisted behavioral patterns derived from session history and HealthKit data.
/// Updated by `UserModelBuilder.dailyUpdate()`.
public struct UserBehavioralPatterns: Codable, Sendable, Equatable {

    // MARK: - Session Patterns

    /// Average session count per mode.
    public var modeFrequency: [String: Int]

    /// Average duration (seconds) per mode.
    public var averageDuration: [String: TimeInterval]

    /// Preferred time-of-day buckets per mode (hour of day → session count).
    public var timeOfDayPreference: [String: [Int: Int]]

    // MARK: - Biometric Response Curves

    /// Average time to calm per mode (seconds). Nil if insufficient data.
    public var averageTimeToCalmByMode: [String: TimeInterval]

    /// Average sleep onset time (seconds). Nil if insufficient data.
    public var averageSleepOnsetTime: TimeInterval?

    /// Average biometric success score per mode.
    public var averageSuccessByMode: [String: Double]

    // MARK: - Mood Patterns

    /// Average check-in mood by day of week (1=Sunday ... 7=Saturday).
    public var moodByDayOfWeek: [Int: Double]

    /// Average check-in mood by hour of day (0-23).
    public var moodByHourOfDay: [Int: Double]

    // MARK: - HealthKit Context

    /// 7-day average resting heart rate. Nil if HealthKit unavailable.
    public var restingHRTrend: Double?

    /// 7-day average HRV (SDNN). Nil if HealthKit unavailable.
    public var hrvTrend: Double?

    /// Last night's sleep hours. Nil if unavailable.
    public var lastSleepHours: Double?

    /// Last night's deep sleep minutes. Nil if unavailable.
    public var lastDeepSleepMinutes: Double?

    /// Today's step count. Nil if unavailable.
    public var stepsToday: Int?

    /// Today's active energy burned in kilocalories. Nil if unavailable.
    public var activeEnergyToday: Double?

    /// Date of last HealthKit data pull.
    public var lastHealthKitUpdate: Date?

    // MARK: - Cross-Signal Correlations

    /// Discovered correlations stored as descriptive entries.
    /// Populated after `crossSignalMinimumSessions` sessions.
    public var correlations: [CrossSignalCorrelation]

    /// Total sessions analyzed.
    public var totalSessionsAnalyzed: Int

    public init() {
        self.modeFrequency = [:]
        self.averageDuration = [:]
        self.timeOfDayPreference = [:]
        self.averageTimeToCalmByMode = [:]
        self.averageSleepOnsetTime = nil
        self.averageSuccessByMode = [:]
        self.moodByDayOfWeek = [:]
        self.moodByHourOfDay = [:]
        self.restingHRTrend = nil
        self.hrvTrend = nil
        self.lastSleepHours = nil
        self.lastDeepSleepMinutes = nil
        self.stepsToday = nil
        self.activeEnergyToday = nil
        self.lastHealthKitUpdate = nil
        self.correlations = []
        self.totalSessionsAnalyzed = 0
    }
}

/// A discovered cross-signal correlation (e.g., "high activity days → rain sounds produce best sleep").
public struct CrossSignalCorrelation: Codable, Sendable, Equatable {

    /// The condition that was tested (e.g., "high_activity_day").
    public let condition: String

    /// The observed effect (e.g., "rain_sounds_improve_sleep_score").
    public let observation: String

    /// Strength of the correlation (0.0 - 1.0).
    public let strength: Double

    /// Number of sessions supporting this correlation.
    public let sampleCount: Int

    public init(condition: String, observation: String, strength: Double, sampleCount: Int) {
        self.condition = condition
        self.observation = observation
        self.strength = strength
        self.sampleCount = sampleCount
    }
}

// MARK: - Patterns Store Protocol

/// Persistence contract for behavioral patterns.
public protocol PatternsStoreProtocol: AnyObject, Sendable {

    /// Loads the stored behavioral patterns, or nil if none exist.
    func loadPatterns() async throws -> UserBehavioralPatterns?

    /// Saves the given behavioral patterns.
    func savePatterns(_ patterns: UserBehavioralPatterns) async throws
}

// MARK: - SwiftData Patterns Model

/// SwiftData persistence wrapper for `UserBehavioralPatterns`.
@Model
public final class UserBehavioralPatternsModel {

    /// JSON-encoded patterns data.
    public var patternsData: Data

    /// Last update timestamp.
    public var lastUpdated: Date

    public init(from patterns: UserBehavioralPatterns, updatedAt: Date) {
        self.patternsData = (try? JSONEncoder().encode(patterns)) ?? Data()
        self.lastUpdated = updatedAt
    }

    public func update(from patterns: UserBehavioralPatterns, updatedAt: Date) {
        self.patternsData = (try? JSONEncoder().encode(patterns)) ?? Data()
        self.lastUpdated = updatedAt
    }

    public func toPatterns() -> UserBehavioralPatterns {
        (try? JSONDecoder().decode(UserBehavioralPatterns.self, from: patternsData))
            ?? UserBehavioralPatterns()
    }
}

// MARK: - User Model Configuration

/// All tuning constants for the user model builder.
public enum UserModelConfig {

    /// Minimum sessions before cross-signal correlation analysis runs.
    static let crossSignalMinimumSessions: Int = 10

    /// Minimum correlation strength to be stored.
    static let minimumCorrelationStrength: Double = 0.3

    /// Number of sessions to look back for pattern analysis.
    static let patternLookbackSessions: Int = 50

    /// Default session durations (seconds) per mode when no history exists.
    static let defaultDurations: [FocusMode: TimeInterval] = [
        .focus: 25 * 60,         // 25 minutes (Pomodoro)
        .relaxation: 15 * 60,    // 15 minutes
        .sleep: 30 * 60          // 30 minutes
    ]

    /// Confidence thresholds for recommendation quality.
    static let lowConfidenceSessionCount: Int = 3
    static let mediumConfidenceSessionCount: Int = 10
    static let highConfidenceSessionCount: Int = 25

    /// Hour ranges for circadian mode suggestions.
    static let morningFocusHours: ClosedRange<Int> = 6...11
    static let afternoonFocusHours: ClosedRange<Int> = 13...17
    static let eveningRelaxHours: ClosedRange<Int> = 18...21
    static let nightSleepHours: ClosedRange<Int> = 21...23
    static let lateNightSleepHours: ClosedRange<Int> = 0...2

    /// Number of days to look back for resting HR and HRV trend averages.
    static let trendLookbackDays: Int = 7

    /// Step count threshold for "high activity day" classification.
    static let highActivityStepThreshold: Int = 10_000

    /// HRV deviation from trend (ms) considered "below baseline".
    static let hrvBelowBaselineThreshold: Double = 5.0

    /// Sleep hours threshold for "poor sleep" classification.
    static let poorSleepThreshold: Double = 5.5

    /// Biometric success threshold for "successful session" in correlation analysis.
    static let correlationSuccessThreshold: Double = 0.7

    /// Biometric success threshold for "poor session" in correlation analysis.
    static let correlationPoorThreshold: Double = 0.3

    /// Minimum sessions per mode needed for correlation analysis subgroups.
    static let correlationMinModeSessions: Int = 5

    /// Mood threshold for "calm" classification in mood-outcome analysis.
    static let calmMoodThreshold: Double = 0.6

    /// Mood threshold for "wired" classification in mood-outcome analysis.
    static let wiredMoodThreshold: Double = 0.4

    /// Default mood when check-in is absent (used in filtering).
    static let defaultMoodFallback: Double = 0.5

    /// Weight of hour-of-day mood prediction vs day-of-week.
    static let moodHourWeight: Double = 0.6

    /// Weight of day-of-week mood prediction vs hour-of-day.
    static let moodDayOfWeekWeight: Double = 0.4

    /// Boost factor for poor-sleep sound overrides.
    static let poorSleepSoundBoost: Double = 1.1

    /// Default resting HR assumption when HealthKit trend unavailable.
    static let defaultRestingHR: Double = 60.0

    /// HRV-to-resting-HR ratio below which HRV is considered "below baseline".
    static let hrvBelowBaselineRatio: Double = 0.8

    /// Biometric success threshold for "working well" reasoning.
    static let workingWellThreshold: Double = 0.7

    // MARK: - Confidence Scores

    static let highConfidenceScore: Double = 0.9
    static let mediumConfidenceScore: Double = 0.6
    static let lowConfidenceScore: Double = 0.3
    static let minimalConfidenceScore: Double = 0.1

    /// Sound tags boosted when user had poor sleep.
    static let poorSleepBoostTags: [String] = ["rain", "ocean", "noise-pink", "noise-brown"]
}

// MARK: - User Model Builder

/// Background learning system that builds a comprehensive behavioral model
/// from session history, HealthKit data, check-in patterns, and cross-signal
/// correlations.
///
/// This is the compounding intelligence layer. Every session, every data point
/// makes the next recommendation smarter. After 10+ sessions, cross-signal
/// correlations emerge. After 25+, recommendations have high confidence.
///
/// All computation is on-device. All dependencies are protocol-based.
public actor UserModelBuilder {

    // MARK: - Dependencies

    private let sessionStore: SessionStoreProtocol
    private let healthKit: HealthKitServiceProtocol
    private let patternsStore: PatternsStoreProtocol
    private let soundProfileManager: SoundProfileManager
    private let dateProvider: DateProviding

    // MARK: - Cached State

    private var patterns: UserBehavioralPatterns?

    // MARK: - Initialization

    public init(
        sessionStore: SessionStoreProtocol,
        healthKit: HealthKitServiceProtocol,
        patternsStore: PatternsStoreProtocol,
        soundProfileManager: SoundProfileManager,
        dateProvider: DateProviding = SystemDateProvider()
    ) {
        self.sessionStore = sessionStore
        self.healthKit = healthKit
        self.patternsStore = patternsStore
        self.soundProfileManager = soundProfileManager
        self.dateProvider = dateProvider
    }

    // MARK: - Daily Update

    /// Pulls fresh HealthKit data, recomputes all behavioral patterns from
    /// session history, and persists the updated model.
    ///
    /// Call this on app launch and once per calendar day.
    public func dailyUpdate() async {
        var updated = await loadPatterns()

        // Pull HealthKit context.
        await updateHealthKitData(&updated)

        // Recompute session patterns from history.
        await updateSessionPatterns(&updated)

        // Run cross-signal correlations if enough data.
        if updated.totalSessionsAnalyzed >= UserModelConfig.crossSignalMinimumSessions {
            await updateCorrelations(&updated)
        }

        patterns = updated
        try? await patternsStore.savePatterns(updated)
    }

    // MARK: - Circadian Mode Suggestion

    /// Suggests a focus mode based on the time of day and user history.
    ///
    /// First checks the user's historical patterns for this hour. If insufficient
    /// data, falls back to circadian defaults (focus in morning, relax in evening,
    /// sleep at night).
    ///
    /// - Parameter time: The current time to base the suggestion on.
    /// - Returns: The suggested mode, or `nil` if no suggestion can be made with confidence.
    public func suggestedMode(at time: Date) async -> FocusMode? {
        let currentPatterns = await loadPatterns()
        let hour = Calendar.current.component(.hour, from: time)

        // Check user's historical preference for this hour.
        let historicalMode = mostFrequentModeAtHour(hour, patterns: currentPatterns)
        if historicalMode != nil {
            return historicalMode
        }

        // Fall back to circadian defaults.
        return circadianDefault(for: hour)
    }

    // MARK: - Session Recommendation

    /// Generates a pre-session recommendation based on the full behavioral model,
    /// current HealthKit context, and time-of-day patterns.
    ///
    /// - Returns: A `SessionRecommendation` with mode, duration, and sound overrides.
    public func sessionRecommendation() async -> SessionRecommendation {
        let now = dateProvider.now()
        let currentPatterns = await loadPatterns()
        let hour = Calendar.current.component(.hour, from: now)
        let dayOfWeek = Calendar.current.component(.weekday, from: now)

        // Determine suggested mode.
        let mode = await suggestedMode(at: now) ?? .focus

        // Determine suggested duration from history.
        let duration = currentPatterns.averageDuration[mode.rawValue]
            ?? UserModelConfig.defaultDurations[mode]
            ?? UserModelConfig.defaultDurations[.focus]!

        // Predict mood from patterns.
        let moodPrediction = predictMood(
            hour: hour,
            dayOfWeek: dayOfWeek,
            patterns: currentPatterns
        )

        // Build sound preference overrides from correlations.
        let soundOverrides = buildSoundOverrides(
            mode: mode,
            patterns: currentPatterns
        )

        // Build reasoning string.
        let reasoning = buildReasoning(
            mode: mode,
            hour: hour,
            patterns: currentPatterns
        )

        // Compute confidence.
        let confidence = computeConfidence(patterns: currentPatterns)

        return SessionRecommendation(
            suggestedMode: mode,
            suggestedDuration: duration,
            moodPrediction: moodPrediction,
            soundPreferenceOverrides: soundOverrides,
            reasoning: reasoning,
            confidence: confidence
        )
    }

    // MARK: - HealthKit Update

    private func updateHealthKitData(_ patterns: inout UserBehavioralPatterns) async {
        guard healthKit.isAvailable else { return }

        // Pull all available HealthKit data in parallel.
        // GAP 5: Use 7-day averages for resting HR and HRV instead of latest single values.
        async let restingHR7Day = healthKit.averageRestingHR(days: UserModelConfig.trendLookbackDays)
        async let hrv7Day = healthKit.averageHRV(days: UserModelConfig.trendLookbackDays)
        async let sleep = healthKit.lastNightSleep()
        async let steps = healthKit.stepsToday()
        async let activeEnergy = healthKit.activeEnergyToday()

        patterns.restingHRTrend = await restingHR7Day
        patterns.hrvTrend = await hrv7Day

        if let sleepData = await sleep {
            patterns.lastSleepHours = sleepData.hours
            patterns.lastDeepSleepMinutes = sleepData.deepSleepMinutes
        }

        patterns.stepsToday = await steps
        patterns.activeEnergyToday = await activeEnergy
        patterns.lastHealthKitUpdate = dateProvider.now()
    }

    // MARK: - Session Pattern Analysis

    private func updateSessionPatterns(_ patterns: inout UserBehavioralPatterns) async {
        guard let outcomes = try? await sessionStore.outcomes(mode: nil) else { return }

        // Take only the most recent N sessions for pattern computation.
        let recentOutcomes = Array(
            outcomes.sorted(by: { $0.startDate > $1.startDate })
                .prefix(UserModelConfig.patternLookbackSessions)
        )

        guard !recentOutcomes.isEmpty else { return }

        patterns.totalSessionsAnalyzed = recentOutcomes.count

        // Mode frequency.
        var modeFreq: [String: Int] = [:]
        for outcome in recentOutcomes {
            modeFreq[outcome.mode.rawValue, default: 0] += 1
        }
        patterns.modeFrequency = modeFreq

        // Average duration per mode.
        var durationSums: [String: (total: TimeInterval, count: Int)] = [:]
        for outcome in recentOutcomes {
            let key = outcome.mode.rawValue
            var entry = durationSums[key, default: (total: 0, count: 0)]
            entry.total += outcome.durationSeconds
            entry.count += 1
            durationSums[key] = entry
        }
        patterns.averageDuration = durationSums.mapValues { $0.total / Double($0.count) }

        // Time-of-day preferences.
        var todPrefs: [String: [Int: Int]] = [:]
        for outcome in recentOutcomes {
            let hour = Calendar.current.component(.hour, from: outcome.startDate)
            let key = outcome.mode.rawValue
            var hourMap = todPrefs[key, default: [:]]
            hourMap[hour, default: 0] += 1
            todPrefs[key] = hourMap
        }
        patterns.timeOfDayPreference = todPrefs

        // Average biometric success per mode.
        var successSums: [String: (total: Double, count: Int)] = [:]
        for outcome in recentOutcomes {
            let key = outcome.mode.rawValue
            var entry = successSums[key, default: (total: 0, count: 0)]
            entry.total += outcome.biometricSuccessScore
            entry.count += 1
            successSums[key] = entry
        }
        patterns.averageSuccessByMode = successSums.mapValues { $0.total / Double($0.count) }

        // Average time to calm per mode.
        var calmSums: [String: (total: TimeInterval, count: Int)] = [:]
        for outcome in recentOutcomes {
            if let t = outcome.timeToCalmSeconds {
                let key = outcome.mode.rawValue
                var entry = calmSums[key, default: (total: 0, count: 0)]
                entry.total += t
                entry.count += 1
                calmSums[key] = entry
            }
        }
        patterns.averageTimeToCalmByMode = calmSums.mapValues { $0.total / Double($0.count) }

        // Average sleep onset time.
        let sleepOnsets = recentOutcomes.compactMap(\.sleepOnsetSeconds)
        if !sleepOnsets.isEmpty {
            patterns.averageSleepOnsetTime = sleepOnsets.reduce(0, +) / Double(sleepOnsets.count)
        }

        // Mood patterns by day of week and hour.
        var moodDOW: [Int: (total: Double, count: Int)] = [:]
        var moodHOD: [Int: (total: Double, count: Int)] = [:]
        for outcome in recentOutcomes {
            guard let mood = outcome.checkInMood else { continue }
            let dow = Calendar.current.component(.weekday, from: outcome.startDate)
            let hour = Calendar.current.component(.hour, from: outcome.startDate)
            var dowEntry = moodDOW[dow, default: (total: 0, count: 0)]
            dowEntry.total += mood
            dowEntry.count += 1
            moodDOW[dow] = dowEntry

            var hodEntry = moodHOD[hour, default: (total: 0, count: 0)]
            hodEntry.total += mood
            hodEntry.count += 1
            moodHOD[hour] = hodEntry
        }
        patterns.moodByDayOfWeek = moodDOW.mapValues { $0.total / Double($0.count) }
        patterns.moodByHourOfDay = moodHOD.mapValues { $0.total / Double($0.count) }
    }

    // MARK: - Cross-Signal Correlations

    /// Runs conditional comparisons across signals to discover patterns.
    ///
    /// Examples of discovered correlations:
    /// - High-activity days: which sounds produce best sleep scores?
    /// - Poor sleep nights: which mode produces best next-day focus?
    /// - Low HRV days: which session duration has highest success?
    private func updateCorrelations(_ patterns: inout UserBehavioralPatterns) async {
        guard let outcomes = try? await sessionStore.outcomes(mode: nil),
              outcomes.count >= UserModelConfig.crossSignalMinimumSessions else { return }

        var discovered: [CrossSignalCorrelation] = []

        // Correlation: High activity days → best sound tags for sleep.
        if let stepsCorrelation = analyzeActivitySoundCorrelation(outcomes: outcomes) {
            discovered.append(stepsCorrelation)
        }

        // Correlation: Time of day → best performing mode.
        let timeCorrelations = analyzeTimeOfDayPerformance(outcomes: outcomes)
        discovered.append(contentsOf: timeCorrelations)

        // Correlation: Check-in mood → biometric success by mode.
        let moodCorrelations = analyzeMoodOutcomeCorrelation(outcomes: outcomes)
        discovered.append(contentsOf: moodCorrelations)

        // Filter to only significant correlations.
        patterns.correlations = discovered.filter {
            $0.strength >= UserModelConfig.minimumCorrelationStrength
        }
    }

    /// Analyzes whether high-activity days correlate with better outcomes
    /// for specific sound tags.
    private func analyzeActivitySoundCorrelation(
        outcomes: [SessionOutcome]
    ) -> CrossSignalCorrelation? {
        // Group sleep sessions by whether they followed a high-activity day.
        // Since we only have step count for today, this uses the pattern
        // of the session's own day context.
        let sleepOutcomes = outcomes.filter { $0.mode == .sleep }
        guard sleepOutcomes.count >= UserModelConfig.correlationMinModeSessions else { return nil }

        // Find the sound tags that appear most in high-success sleep sessions.
        let successfulSessions = sleepOutcomes.filter {
            $0.biometricSuccessScore > UserModelConfig.correlationSuccessThreshold
        }
        let poorSessions = sleepOutcomes.filter {
            $0.biometricSuccessScore < UserModelConfig.correlationPoorThreshold
        }

        guard !successfulSessions.isEmpty, !poorSessions.isEmpty else { return nil }

        // Count tag frequencies in successful vs poor sessions.
        var successTags: [String: Int] = [:]
        for session in successfulSessions {
            for tag in session.activeSoundTags {
                successTags[tag, default: 0] += 1
            }
        }

        var poorTags: [String: Int] = [:]
        for session in poorSessions {
            for tag in session.activeSoundTags {
                poorTags[tag, default: 0] += 1
            }
        }

        // Find tags that appear disproportionately in successful sessions.
        guard let bestTag = successTags.max(by: { $0.value < $1.value }) else { return nil }

        let successRate = Double(bestTag.value) / Double(successfulSessions.count)
        let poorRate = Double(poorTags[bestTag.key, default: 0]) / Double(poorSessions.count)

        let strength = max(0, successRate - poorRate)

        return CrossSignalCorrelation(
            condition: "sleep_sessions",
            observation: "\(bestTag.key)_correlates_with_success",
            strength: strength,
            sampleCount: sleepOutcomes.count
        )
    }

    /// Analyzes which times of day produce the best outcomes per mode.
    private func analyzeTimeOfDayPerformance(
        outcomes: [SessionOutcome]
    ) -> [CrossSignalCorrelation] {
        var results: [CrossSignalCorrelation] = []

        for mode in FocusMode.allCases {
            let modeOutcomes = outcomes.filter { $0.mode == mode }
            guard modeOutcomes.count >= UserModelConfig.correlationMinModeSessions else { continue }

            // Group by morning (6-12), afternoon (12-18), evening (18-24), night (0-6).
            let buckets: [(name: String, range: ClosedRange<Int>)] = [
                ("morning", 6...11),
                ("afternoon", 12...17),
                ("evening", 18...23),
                ("night", 0...5)
            ]

            var bestBucket = ""
            var bestScore: Double = 0

            for bucket in buckets {
                let bucketOutcomes = modeOutcomes.filter {
                    let hour = Calendar.current.component(.hour, from: $0.startDate)
                    return bucket.range.contains(hour)
                }
                guard !bucketOutcomes.isEmpty else { continue }

                let avgScore = bucketOutcomes.reduce(0.0) {
                    $0 + $1.biometricSuccessScore
                } / Double(bucketOutcomes.count)

                if avgScore > bestScore {
                    bestScore = avgScore
                    bestBucket = bucket.name
                }
            }

            if !bestBucket.isEmpty {
                results.append(CrossSignalCorrelation(
                    condition: "\(mode.rawValue)_time_of_day",
                    observation: "\(bestBucket)_produces_best_outcomes",
                    strength: bestScore,
                    sampleCount: modeOutcomes.count
                ))
            }
        }

        return results
    }

    /// Analyzes whether initial mood state predicts biometric success by mode.
    private func analyzeMoodOutcomeCorrelation(
        outcomes: [SessionOutcome]
    ) -> [CrossSignalCorrelation] {
        var results: [CrossSignalCorrelation] = []

        for mode in FocusMode.allCases {
            let modeOutcomes = outcomes.filter {
                $0.mode == mode && $0.checkInMood != nil
            }
            guard modeOutcomes.count >= UserModelConfig.correlationMinModeSessions else { continue }

            // Split into high-mood (calm) and low-mood (wired) groups.
            let highMood = modeOutcomes.filter {
                ($0.checkInMood ?? UserModelConfig.defaultMoodFallback) > UserModelConfig.calmMoodThreshold
            }
            let lowMood = modeOutcomes.filter {
                ($0.checkInMood ?? UserModelConfig.defaultMoodFallback) < UserModelConfig.wiredMoodThreshold
            }

            guard !highMood.isEmpty, !lowMood.isEmpty else { continue }

            let highAvg = highMood.reduce(0.0) { $0 + $1.biometricSuccessScore } / Double(highMood.count)
            let lowAvg = lowMood.reduce(0.0) { $0 + $1.biometricSuccessScore } / Double(lowMood.count)

            let delta = abs(highAvg - lowAvg)
            let observation = highAvg > lowAvg
                ? "calm_mood_improves_outcomes"
                : "wired_mood_improves_outcomes"

            results.append(CrossSignalCorrelation(
                condition: "\(mode.rawValue)_mood_correlation",
                observation: observation,
                strength: delta,
                sampleCount: modeOutcomes.count
            ))
        }

        return results
    }

    // MARK: - Recommendation Helpers

    /// Returns the mode the user most frequently uses at this hour.
    private func mostFrequentModeAtHour(
        _ hour: Int,
        patterns: UserBehavioralPatterns
    ) -> FocusMode? {
        var bestMode: FocusMode?
        var bestCount = 0

        for mode in FocusMode.allCases {
            let count = patterns.timeOfDayPreference[mode.rawValue]?[hour] ?? 0
            if count > bestCount {
                bestCount = count
                bestMode = mode
            }
        }

        // Require at least 3 sessions at this hour to trust the pattern.
        guard bestCount >= UserModelConfig.lowConfidenceSessionCount else { return nil }
        return bestMode
    }

    /// Returns the circadian default mode for a given hour.
    private func circadianDefault(for hour: Int) -> FocusMode {
        if UserModelConfig.morningFocusHours.contains(hour)
            || UserModelConfig.afternoonFocusHours.contains(hour) {
            return .focus
        } else if UserModelConfig.eveningRelaxHours.contains(hour) {
            return .relaxation
        } else if UserModelConfig.nightSleepHours.contains(hour)
                    || UserModelConfig.lateNightSleepHours.contains(hour) {
            return .sleep
        } else {
            return .focus
        }
    }

    /// Predicts the user's mood at the given time based on historical patterns.
    private func predictMood(
        hour: Int,
        dayOfWeek: Int,
        patterns: UserBehavioralPatterns
    ) -> Double? {
        let hourMood = patterns.moodByHourOfDay[hour]
        let dowMood = patterns.moodByDayOfWeek[dayOfWeek]

        switch (hourMood, dowMood) {
        case let (.some(h), .some(d)):
            // Weighted average: hour-of-day patterns are more predictive.
            return h * UserModelConfig.moodHourWeight + d * UserModelConfig.moodDayOfWeekWeight
        case let (.some(h), .none):
            return h
        case let (.none, .some(d)):
            return d
        case (.none, .none):
            return nil
        }
    }

    /// Builds sound preference overrides from correlations and current context.
    private func buildSoundOverrides(
        mode: FocusMode,
        patterns: UserBehavioralPatterns
    ) -> [String: Double] {
        var overrides: [String: Double] = [:]

        // Apply any discovered correlations for this mode.
        for correlation in patterns.correlations {
            guard correlation.condition.hasPrefix(mode.rawValue),
                  correlation.strength >= UserModelConfig.minimumCorrelationStrength else { continue }

            // Extract the tag name from the observation.
            let parts = correlation.observation.split(separator: "_")
            if let tagName = parts.first {
                let boost = 0.5 + correlation.strength
                overrides[String(tagName)] = boost
            }
        }

        // If user had poor sleep, boost calming sounds for all modes.
        if let sleepHours = patterns.lastSleepHours,
           sleepHours < UserModelConfig.poorSleepThreshold {
            for tag in UserModelConfig.poorSleepBoostTags {
                overrides[tag, default: 0.5] *= UserModelConfig.poorSleepSoundBoost
            }
        }

        return overrides
    }

    /// Builds a human-readable reasoning string for the recommendation.
    private func buildReasoning(
        mode: FocusMode,
        hour: Int,
        patterns: UserBehavioralPatterns
    ) -> String {
        var reasons: [String] = []

        // Time-based reasoning.
        let historicalMode = mostFrequentModeAtHour(hour, patterns: patterns)
        if historicalMode == mode {
            reasons.append("You typically use \(mode.displayName) at this time")
        }

        // HRV context.
        if let hrv = patterns.hrvTrend {
            if hrv < (patterns.restingHRTrend ?? UserModelConfig.defaultRestingHR) * UserModelConfig.hrvBelowBaselineRatio {
                reasons.append("Your HRV is below your baseline today")
            }
        }

        // Sleep context.
        if let sleepHours = patterns.lastSleepHours {
            if sleepHours < UserModelConfig.poorSleepThreshold {
                reasons.append("You had a short sleep last night (\(String(format: "%.1f", sleepHours))h)")
            }
        }

        // Activity context.
        if let steps = patterns.stepsToday,
           steps >= UserModelConfig.highActivityStepThreshold {
            reasons.append("High activity today (\(steps) steps)")
        }

        // Success history.
        if let avgSuccess = patterns.averageSuccessByMode[mode.rawValue],
           avgSuccess > UserModelConfig.workingWellThreshold {
            reasons.append("\(mode.displayName) sessions have been working well for you")
        }

        if reasons.isEmpty {
            return "Based on your time of day and general patterns"
        }

        return reasons.joined(separator: ". ")
    }

    /// Computes recommendation confidence based on data quantity.
    private func computeConfidence(patterns: UserBehavioralPatterns) -> Double {
        let count = patterns.totalSessionsAnalyzed
        if count >= UserModelConfig.highConfidenceSessionCount {
            return UserModelConfig.highConfidenceScore
        } else if count >= UserModelConfig.mediumConfidenceSessionCount {
            return UserModelConfig.mediumConfidenceScore
        } else if count >= UserModelConfig.lowConfidenceSessionCount {
            return UserModelConfig.lowConfidenceScore
        } else {
            return UserModelConfig.minimalConfidenceScore
        }
    }

    // MARK: - Pattern Loading

    private func loadPatterns() async -> UserBehavioralPatterns {
        if let cached = patterns {
            return cached
        }
        let loaded = try? await patternsStore.loadPatterns()
        let result = loaded ?? UserBehavioralPatterns()
        patterns = result
        return result
    }
}
