// StemMetadata.swift
// BioNaural
//
// Data models for stem-separated audio packs. A stem pack contains
// 3-4 audio files (pads, texture, bass, optional rhythm) meant to be
// played simultaneously with independent per-stem volume control.
// BiometricStemMixer adjusts volumes in real time based on HR/HRV.
//
// All tag values follow the same schema as SoundMetadata for
// consistency with the existing SoundSelector pipeline.

import BioNauralShared
import Foundation

// MARK: - Stem Slot

/// Identifies a stem within a pack. Each slot has a distinct role
/// in the biometric mixing rules defined by `BiometricStemMixer`.
public enum StemSlot: String, Codable, CaseIterable, Sendable {

    /// Warm sustained tones — volume increases when HR is elevated
    /// (calming effect in Focus/Relax/Sleep).
    case pads

    /// Atmospheric detail — volume decreases when HR is elevated
    /// to reduce stimulation.
    case texture

    /// Low-frequency body — remains relatively stable to anchor the mix.
    case bass

    /// Percussive elements — removed in Sleep, reduced in Focus/Relax
    /// when HR is elevated, increased in Energize.
    case rhythm
}

// MARK: - Stem Volume Targets

/// Per-stem volume snapshot produced by `BiometricStemMixer`.
/// All values are normalized `[0.0 ... 1.0]`.
public struct StemVolumeTargets: Sendable, Equatable {

    public let pads: Float
    public let texture: Float
    public let bass: Float
    public let rhythm: Float

    public init(pads: Float, texture: Float, bass: Float, rhythm: Float) {
        self.pads = pads
        self.texture = texture
        self.bass = bass
        self.rhythm = rhythm
    }

    /// Returns the volume for a specific stem slot.
    public subscript(slot: StemSlot) -> Float {
        switch slot {
        case .pads:    return pads
        case .texture: return texture
        case .bass:    return bass
        case .rhythm:  return rhythm
        }
    }
}

// MARK: - Stem Pack Metadata

/// Describes a stem pack — a set of audio files meant to be played
/// simultaneously with independent volume control per stem.
///
/// Metadata is loaded from a `metadata.json` file inside each
/// content pack directory managed by `ContentPackManager`.
public struct StemPackMetadata: Codable, Identifiable, Sendable {

    /// Unique pack identifier (matches the directory name).
    public let id: String

    /// Human-readable name (e.g., "Warm Focus Ambient").
    public let name: String

    // MARK: - Stem File Names

    /// Filename for the pads stem (relative to the pack directory).
    public let padsFileName: String

    /// Filename for the texture stem.
    public let textureFileName: String

    /// Filename for the bass stem.
    public let bassFileName: String

    /// Filename for the rhythm stem. `nil` if the pack has no
    /// percussive content (common for Sleep packs).
    public let rhythmFileName: String?

    // MARK: - Tags (Same Schema as SoundMetadata)

    /// Activating vs. calming — `0.0` = deep sleep, `1.0` = high energy.
    public let energy: Double

    /// Spectral brightness — `0.0` = dark/warm, `1.0` = bright/airy.
    public let brightness: Double

    /// Spectral warmth — `0.0` = cold/clinical, `1.0` = warm/rich.
    public let warmth: Double

    /// Tempo in BPM. `nil` for arrhythmic/free-time packs.
    public let tempo: Double?

    /// Musical key (e.g., `"A"`, `"C#"`). `nil` for atonal content.
    public let key: String?

    /// Which focus modes this pack is designed for.
    public let modeAffinity: [FocusMode]

    // MARK: - Source Metadata

    /// How this pack was created.
    public let generatedBy: StemPackSource

    /// The text prompt used for AI generation. `nil` for
    /// manually produced or Demucs-separated packs.
    public let generationPrompt: String?

    // MARK: - CodingKeys

    private enum CodingKeys: String, CodingKey {
        case id, name
        case padsFileName, textureFileName, bassFileName, rhythmFileName
        case energy, brightness, warmth, tempo, key, modeAffinity
        case generatedBy, generationPrompt
    }
}

// MARK: - Stem Pack Source

/// How a stem pack was produced.
public enum StemPackSource: String, Codable, Sendable {

    /// Generated by ACE-Step 1.5 on server, separated by Demucs.
    case aceStep = "ace-step-1.5"

    /// Separated from existing licensed audio via Demucs.
    case demucs

    /// Hand-crafted by a sound designer.
    case manual
}
